name: Mark stale issues and pull requests

on:
  repository_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: my test
        run: |
          cd $GITHUB_WORKSPACE
          ls
          echo ${{ github.event.client_payload.institution }}
